// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// blue.cpp
cpp11::writable::doubles blue_c(cpp11::integers dim, int n_seeds, SEXP seed, cpp11::doubles kernel);
extern "C" SEXP _ambient_blue_c(SEXP dim, SEXP n_seeds, SEXP seed, SEXP kernel) {
  BEGIN_CPP11
    return cpp11::as_sexp(blue_c(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(dim), cpp11::as_cpp<cpp11::decay_t<int>>(n_seeds), cpp11::as_cpp<cpp11::decay_t<SEXP>>(seed), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(kernel)));
  END_CPP11
}
// cubic.cpp
cpp11::writable::doubles_matrix cubic_2d_c(int height, int width, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_cubic_2d_c(SEXP height, SEXP width, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(cubic_2d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// cubic.cpp
cpp11::writable::doubles_matrix cubic_3d_c(int height, int width, int depth, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_cubic_3d_c(SEXP height, SEXP width, SEXP depth, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(cubic_3d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// cubic.cpp
cpp11::writable::doubles gen_cubic2d_c(cpp11::doubles x, cpp11::doubles y, double freq, int seed);
extern "C" SEXP _ambient_gen_cubic2d_c(SEXP x, SEXP y, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_cubic2d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// cubic.cpp
cpp11::writable::doubles gen_cubic3d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double freq, int seed);
extern "C" SEXP _ambient_gen_cubic3d_c(SEXP x, SEXP y, SEXP z, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_cubic3d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// perlin.cpp
cpp11::writable::doubles_matrix perlin_2d_c(int height, int width, int seed, double freq, int interp, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_perlin_2d_c(SEXP height, SEXP width, SEXP seed, SEXP freq, SEXP interp, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(perlin_2d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(interp), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// perlin.cpp
cpp11::writable::doubles_matrix perlin_3d_c(int height, int width, int depth, int seed, double freq, int interp, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_perlin_3d_c(SEXP height, SEXP width, SEXP depth, SEXP seed, SEXP freq, SEXP interp, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(perlin_3d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(interp), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// perlin.cpp
cpp11::writable::doubles gen_perlin2d_c(cpp11::doubles x, cpp11::doubles y, double freq, int seed, int interp);
extern "C" SEXP _ambient_gen_perlin2d_c(SEXP x, SEXP y, SEXP freq, SEXP seed, SEXP interp) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_perlin2d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(interp)));
  END_CPP11
}
// perlin.cpp
cpp11::writable::doubles gen_perlin3d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double freq, int seed, int interp);
extern "C" SEXP _ambient_gen_perlin3d_c(SEXP x, SEXP y, SEXP z, SEXP freq, SEXP seed, SEXP interp) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_perlin3d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(interp)));
  END_CPP11
}
// simplex.cpp
cpp11::writable::doubles_matrix simplex_2d_c(int height, int width, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_simplex_2d_c(SEXP height, SEXP width, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_2d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// simplex.cpp
cpp11::writable::doubles_matrix simplex_3d_c(int height, int width, int depth, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_simplex_3d_c(SEXP height, SEXP width, SEXP depth, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_3d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// simplex.cpp
cpp11::writable::doubles_matrix simplex_4d_c(int height, int width, int depth, int time, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_simplex_4d_c(SEXP height, SEXP width, SEXP depth, SEXP time, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(simplex_4d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(time), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// simplex.cpp
cpp11::writable::doubles gen_simplex2d_c(cpp11::doubles x, cpp11::doubles y, double freq, int seed);
extern "C" SEXP _ambient_gen_simplex2d_c(SEXP x, SEXP y, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_simplex2d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// simplex.cpp
cpp11::writable::doubles gen_simplex3d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double freq, int seed);
extern "C" SEXP _ambient_gen_simplex3d_c(SEXP x, SEXP y, SEXP z, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_simplex3d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// simplex.cpp
cpp11::writable::doubles gen_simplex4d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, cpp11::doubles t, double freq, int seed);
extern "C" SEXP _ambient_gen_simplex4d_c(SEXP x, SEXP y, SEXP z, SEXP t, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_simplex4d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(t), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// value.cpp
cpp11::writable::doubles_matrix value_2d_c(int height, int width, int seed, double freq, int interp, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_value_2d_c(SEXP height, SEXP width, SEXP seed, SEXP freq, SEXP interp, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(value_2d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(interp), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// value.cpp
cpp11::writable::doubles_matrix value_3d_c(int height, int width, int depth, int seed, double freq, int interp, int fractal, int octaves, double lacunarity, double gain, int pertube, double pertube_amp);
extern "C" SEXP _ambient_value_3d_c(SEXP height, SEXP width, SEXP depth, SEXP seed, SEXP freq, SEXP interp, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(value_3d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(interp), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// value.cpp
cpp11::writable::doubles gen_value2d_c(cpp11::doubles x, cpp11::doubles y, double freq, int seed, int interp);
extern "C" SEXP _ambient_gen_value2d_c(SEXP x, SEXP y, SEXP freq, SEXP seed, SEXP interp) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_value2d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(interp)));
  END_CPP11
}
// value.cpp
cpp11::writable::doubles gen_value3d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double freq, int seed, int interp);
extern "C" SEXP _ambient_gen_value3d_c(SEXP x, SEXP y, SEXP z, SEXP freq, SEXP seed, SEXP interp) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_value3d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(interp)));
  END_CPP11
}
// white.cpp
cpp11::writable::doubles_matrix white_2d_c(int height, int width, int seed, double freq, int pertube, double pertube_amp);
extern "C" SEXP _ambient_white_2d_c(SEXP height, SEXP width, SEXP seed, SEXP freq, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(white_2d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// white.cpp
cpp11::writable::doubles_matrix white_3d_c(int height, int width, int depth, int seed, double freq, int pertube, double pertube_amp);
extern "C" SEXP _ambient_white_3d_c(SEXP height, SEXP width, SEXP depth, SEXP seed, SEXP freq, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(white_3d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// white.cpp
cpp11::writable::doubles_matrix white_4d_c(int height, int width, int depth, int time, int seed, double freq, int pertube, double pertube_amp);
extern "C" SEXP _ambient_white_4d_c(SEXP height, SEXP width, SEXP depth, SEXP time, SEXP seed, SEXP freq, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(white_4d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(time), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// white.cpp
cpp11::writable::doubles gen_white2d_c(cpp11::doubles x, cpp11::doubles y, double freq, int seed);
extern "C" SEXP _ambient_gen_white2d_c(SEXP x, SEXP y, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_white2d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// white.cpp
cpp11::writable::doubles gen_white3d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double freq, int seed);
extern "C" SEXP _ambient_gen_white3d_c(SEXP x, SEXP y, SEXP z, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_white3d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// white.cpp
cpp11::writable::doubles gen_white4d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, cpp11::doubles t, double freq, int seed);
extern "C" SEXP _ambient_gen_white4d_c(SEXP x, SEXP y, SEXP z, SEXP t, SEXP freq, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_white4d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(t), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// worley.cpp
cpp11::writable::doubles_matrix worley_2d_c(int height, int width, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int dist, int value, cpp11::integers dist2ind, double jitter, int pertube, double pertube_amp);
extern "C" SEXP _ambient_worley_2d_c(SEXP height, SEXP width, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP dist, SEXP value, SEXP dist2ind, SEXP jitter, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(worley_2d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(dist), cpp11::as_cpp<cpp11::decay_t<int>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(dist2ind), cpp11::as_cpp<cpp11::decay_t<double>>(jitter), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// worley.cpp
cpp11::writable::doubles_matrix worley_3d_c(int height, int width, int depth, int seed, double freq, int fractal, int octaves, double lacunarity, double gain, int dist, int value, cpp11::integers dist2ind, double jitter, int pertube, double pertube_amp);
extern "C" SEXP _ambient_worley_3d_c(SEXP height, SEXP width, SEXP depth, SEXP seed, SEXP freq, SEXP fractal, SEXP octaves, SEXP lacunarity, SEXP gain, SEXP dist, SEXP value, SEXP dist2ind, SEXP jitter, SEXP pertube, SEXP pertube_amp) {
  BEGIN_CPP11
    return cpp11::as_sexp(worley_3d_c(cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(fractal), cpp11::as_cpp<cpp11::decay_t<int>>(octaves), cpp11::as_cpp<cpp11::decay_t<double>>(lacunarity), cpp11::as_cpp<cpp11::decay_t<double>>(gain), cpp11::as_cpp<cpp11::decay_t<int>>(dist), cpp11::as_cpp<cpp11::decay_t<int>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(dist2ind), cpp11::as_cpp<cpp11::decay_t<double>>(jitter), cpp11::as_cpp<cpp11::decay_t<int>>(pertube), cpp11::as_cpp<cpp11::decay_t<double>>(pertube_amp)));
  END_CPP11
}
// worley.cpp
cpp11::writable::doubles gen_worley2d_c(cpp11::doubles x, cpp11::doubles y, double freq, int seed, int dist, int value, cpp11::integers dist2ind, double jitter);
extern "C" SEXP _ambient_gen_worley2d_c(SEXP x, SEXP y, SEXP freq, SEXP seed, SEXP dist, SEXP value, SEXP dist2ind, SEXP jitter) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_worley2d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(dist), cpp11::as_cpp<cpp11::decay_t<int>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(dist2ind), cpp11::as_cpp<cpp11::decay_t<double>>(jitter)));
  END_CPP11
}
// worley.cpp
cpp11::writable::doubles gen_worley3d_c(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double freq, int seed, int dist, int value, cpp11::integers dist2ind, double jitter);
extern "C" SEXP _ambient_gen_worley3d_c(SEXP x, SEXP y, SEXP z, SEXP freq, SEXP seed, SEXP dist, SEXP value, SEXP dist2ind, SEXP jitter) {
  BEGIN_CPP11
    return cpp11::as_sexp(gen_worley3d_c(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(freq), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(dist), cpp11::as_cpp<cpp11::decay_t<int>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(dist2ind), cpp11::as_cpp<cpp11::decay_t<double>>(jitter)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _ambient_blue_c(SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_cubic_2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_cubic_3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_cubic2d_c(SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_cubic3d_c(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_perlin2d_c(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_perlin3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_simplex2d_c(SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_simplex3d_c(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_simplex4d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_value2d_c(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_value3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_white2d_c(SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_white3d_c(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_white4d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_worley2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_gen_worley3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_perlin_2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_perlin_3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_simplex_2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_simplex_3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_simplex_4d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_value_2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_value_3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_white_2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_white_3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_white_4d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_worley_2d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _ambient_worley_3d_c(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ambient_blue_c",          (DL_FUNC) &_ambient_blue_c,           4},
    {"_ambient_cubic_2d_c",      (DL_FUNC) &_ambient_cubic_2d_c,      10},
    {"_ambient_cubic_3d_c",      (DL_FUNC) &_ambient_cubic_3d_c,      11},
    {"_ambient_gen_cubic2d_c",   (DL_FUNC) &_ambient_gen_cubic2d_c,    4},
    {"_ambient_gen_cubic3d_c",   (DL_FUNC) &_ambient_gen_cubic3d_c,    5},
    {"_ambient_gen_perlin2d_c",  (DL_FUNC) &_ambient_gen_perlin2d_c,   5},
    {"_ambient_gen_perlin3d_c",  (DL_FUNC) &_ambient_gen_perlin3d_c,   6},
    {"_ambient_gen_simplex2d_c", (DL_FUNC) &_ambient_gen_simplex2d_c,  4},
    {"_ambient_gen_simplex3d_c", (DL_FUNC) &_ambient_gen_simplex3d_c,  5},
    {"_ambient_gen_simplex4d_c", (DL_FUNC) &_ambient_gen_simplex4d_c,  6},
    {"_ambient_gen_value2d_c",   (DL_FUNC) &_ambient_gen_value2d_c,    5},
    {"_ambient_gen_value3d_c",   (DL_FUNC) &_ambient_gen_value3d_c,    6},
    {"_ambient_gen_white2d_c",   (DL_FUNC) &_ambient_gen_white2d_c,    4},
    {"_ambient_gen_white3d_c",   (DL_FUNC) &_ambient_gen_white3d_c,    5},
    {"_ambient_gen_white4d_c",   (DL_FUNC) &_ambient_gen_white4d_c,    6},
    {"_ambient_gen_worley2d_c",  (DL_FUNC) &_ambient_gen_worley2d_c,   8},
    {"_ambient_gen_worley3d_c",  (DL_FUNC) &_ambient_gen_worley3d_c,   9},
    {"_ambient_perlin_2d_c",     (DL_FUNC) &_ambient_perlin_2d_c,     11},
    {"_ambient_perlin_3d_c",     (DL_FUNC) &_ambient_perlin_3d_c,     12},
    {"_ambient_simplex_2d_c",    (DL_FUNC) &_ambient_simplex_2d_c,    10},
    {"_ambient_simplex_3d_c",    (DL_FUNC) &_ambient_simplex_3d_c,    11},
    {"_ambient_simplex_4d_c",    (DL_FUNC) &_ambient_simplex_4d_c,    12},
    {"_ambient_value_2d_c",      (DL_FUNC) &_ambient_value_2d_c,      11},
    {"_ambient_value_3d_c",      (DL_FUNC) &_ambient_value_3d_c,      12},
    {"_ambient_white_2d_c",      (DL_FUNC) &_ambient_white_2d_c,       6},
    {"_ambient_white_3d_c",      (DL_FUNC) &_ambient_white_3d_c,       7},
    {"_ambient_white_4d_c",      (DL_FUNC) &_ambient_white_4d_c,       8},
    {"_ambient_worley_2d_c",     (DL_FUNC) &_ambient_worley_2d_c,     14},
    {"_ambient_worley_3d_c",     (DL_FUNC) &_ambient_worley_3d_c,     15},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_ambient(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
