# Generated by cpp11: do not edit by hand

cubic_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_cubic_2d_c", height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

cubic_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_cubic_3d_c", height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

gen_cubic2d_c <- function(x, y, freq, seed) {
  .Call("_ambient_gen_cubic2d_c", x, y, freq, seed, PACKAGE = "ambient")
}

gen_cubic3d_c <- function(x, y, z, freq, seed) {
  .Call("_ambient_gen_cubic3d_c", x, y, z, freq, seed, PACKAGE = "ambient")
}

perlin_2d_c <- function(height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_perlin_2d_c", height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

perlin_3d_c <- function(height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_perlin_3d_c", height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

gen_perlin2d_c <- function(x, y, freq, seed, interp) {
  .Call("_ambient_gen_perlin2d_c", x, y, freq, seed, interp, PACKAGE = "ambient")
}

gen_perlin3d_c <- function(x, y, z, freq, seed, interp) {
  .Call("_ambient_gen_perlin3d_c", x, y, z, freq, seed, interp, PACKAGE = "ambient")
}

simplex_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_simplex_2d_c", height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

simplex_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_simplex_3d_c", height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

simplex_4d_c <- function(height, width, depth, time, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_simplex_4d_c", height, width, depth, time, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

gen_simplex2d_c <- function(x, y, freq, seed) {
  .Call("_ambient_gen_simplex2d_c", x, y, freq, seed, PACKAGE = "ambient")
}

gen_simplex3d_c <- function(x, y, z, freq, seed) {
  .Call("_ambient_gen_simplex3d_c", x, y, z, freq, seed, PACKAGE = "ambient")
}

gen_simplex4d_c <- function(x, y, z, t, freq, seed) {
  .Call("_ambient_gen_simplex4d_c", x, y, z, t, freq, seed, PACKAGE = "ambient")
}

value_2d_c <- function(height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_value_2d_c", height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

value_3d_c <- function(height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
  .Call("_ambient_value_3d_c", height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp, PACKAGE = "ambient")
}

gen_value2d_c <- function(x, y, freq, seed, interp) {
  .Call("_ambient_gen_value2d_c", x, y, freq, seed, interp, PACKAGE = "ambient")
}

gen_value3d_c <- function(x, y, z, freq, seed, interp) {
  .Call("_ambient_gen_value3d_c", x, y, z, freq, seed, interp, PACKAGE = "ambient")
}

white_2d_c <- function(height, width, seed, freq, pertube, pertube_amp) {
  .Call("_ambient_white_2d_c", height, width, seed, freq, pertube, pertube_amp, PACKAGE = "ambient")
}

white_3d_c <- function(height, width, depth, seed, freq, pertube, pertube_amp) {
  .Call("_ambient_white_3d_c", height, width, depth, seed, freq, pertube, pertube_amp, PACKAGE = "ambient")
}

white_4d_c <- function(height, width, depth, time, seed, freq, pertube, pertube_amp) {
  .Call("_ambient_white_4d_c", height, width, depth, time, seed, freq, pertube, pertube_amp, PACKAGE = "ambient")
}

gen_white2d_c <- function(x, y, freq, seed) {
  .Call("_ambient_gen_white2d_c", x, y, freq, seed, PACKAGE = "ambient")
}

gen_white3d_c <- function(x, y, z, freq, seed) {
  .Call("_ambient_gen_white3d_c", x, y, z, freq, seed, PACKAGE = "ambient")
}

gen_white4d_c <- function(x, y, z, t, freq, seed) {
  .Call("_ambient_gen_white4d_c", x, y, z, t, freq, seed, PACKAGE = "ambient")
}

worley_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp) {
  .Call("_ambient_worley_2d_c", height, width, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp, PACKAGE = "ambient")
}

worley_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp) {
  .Call("_ambient_worley_3d_c", height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp, PACKAGE = "ambient")
}

gen_worley2d_c <- function(x, y, freq, seed, dist, value, dist2ind, jitter) {
  .Call("_ambient_gen_worley2d_c", x, y, freq, seed, dist, value, dist2ind, jitter, PACKAGE = "ambient")
}

gen_worley3d_c <- function(x, y, z, freq, seed, dist, value, dist2ind, jitter) {
  .Call("_ambient_gen_worley3d_c", x, y, z, freq, seed, dist, value, dist2ind, jitter, PACKAGE = "ambient")
}
