#' Generate curl noise
#'
#' One of the use cases for fractal noise is to simulate natural phenomena.
#' perlin/simplex noise are e.g. often used to create flow fields, but this can
#' be problematic as they are not divergence-free (particles will concentrate at
#' sinks/gutters in the field). An approach to avoid this is to take the curl of
#' a field instead. The curl operator is ensured to produce divergence-free
#' output, when supplied with continuous fields such as those generated by
#' simplex and perlin noise. The end result is a field that is incompressible,
#' thus modelling fluid dynamics quite well.
#'
#' @param grid A long_grid object or a data.frame
#' @param generator The noise generating function, such as [gen_simplex], or
#' [fracture()]
#' @param x,y,z The coordinates to generate the curl for as unquoted expressions
#' @param ... Further arguments to `generator`
#' @param seed A seed for the generator. For 2D curl the seed is a single
#' integer and for 3D curl it must be a vector of 3 integers. If `NULL` the
#' seeds will be random.
#' @param delta The offset to use for the partial derivative of the `generator`.
#' If `NULL`, it will be set as 1e-4 of the largest range of the dimensions.
#' @param output The name to save the generated fields in. Must be a character
#' vector with 2 or 3 strings in, for 2D and 3D curl respectively. If `NULL`
#' they will be derived from `x`, `y` (, and `z`)
#'
#' @export
#'
#' @references
#' Bridson, Robert. Hourihan, Jim. Nordenstam, Marcus (2007). *Curl-noise for procedural fluid flow*.
#' ACM Transactions on Graphics 26(3): 46. doi:10.1145/1275808.1276435.
#'
#' @examples
#' grid <- long_grid(seq(0, 1, l = 100), seq(0, 1, l = 100))
#'
#' # Use one of the generators
#' grid <- curl_noise(grid, gen_simplex, x = x, y = y, output = c('x1', 'y1'))
#' plot(grid$x, grid$y, type = 'n')
#' segments(grid$x, grid$y, grid$x + grid$x1 / 100, grid$y + grid$y1 / 100)
#'
#' # If the curl of fractal noise is needed, pass in `fracture` instead
#' grid <- curl_noise(grid, fracture, noise = gen_simplex, fractal = fbm,
#'                    octaves = 4, x = x, y = y, output = c('x1', 'y1'))
#' plot(grid$x, grid$y, type = 'n')
#' segments(grid$x, grid$y, grid$x + grid$x1 / 500, grid$y + grid$y1 / 500)
#'
curl_noise <- function(grid, generator, x, y, z = NULL, ..., seed = NULL, delta = NULL, output = NULL) {
  x <- enquo(x)
  y <- enquo(y)
  z <- enquo(z)
  if (is.null(output)) {
    output <- c(quo_name(x), quo_name(y), quo_name(z))
  }
  x <- eval_tidy(x, grid)
  y <- eval_tidy(y, grid)
  z <- eval_tidy(z, grid)

  if (is.null(z) || length(z) == 1) {
    vel <- .curl_noise2d(generator, x, y, z = z, ...,
                         seed = seed, delta = delta)
    grid[[output[1]]] <- vel$x
    grid[[output[2]]] <- vel$y
  } else {
    vel <- .curl_noise3d(generator, eval_tidy(x, grid), eval_tidy(y, grid),
                         eval_tidy(z, grid), ..., seed = seed, delta = delta)
    grid[[output[1]]] <- vel$x
    grid[[output[2]]] <- vel$y
    grid[[output[3]]] <- vel$z
  }
  grid
}

.curl_noise2d <- function(generator, x, y, ..., seed = NULL, delta = NULL) {
  if (is.null(seed)) seed <- random_seed()
  if (is.null(delta)) {
    delta <- max(diff(range(x)), diff(range(y))) * 1e-4
  }
  velocity_x <- generator(x = x, y = y + delta, seed = seed, ...) -
    generator(x = x, y = y - delta, seed = seed, ...)
  velocity_x <- -velocity_x / (2 * delta)

  velocity_y <- generator(x = x + delta, y = y, seed = seed, ...) -
    generator(x = x - delta, y = y, seed = seed, ...)
  velocity_y <- velocity_y / (2 * delta)
  list(x = velocity_x, y = velocity_y)
}

.curl_noise3d <- function(generator, x, y, z, ..., seed = NULL, delta = NULL) {
  if (is.null(seed)) seed <- c(random_seed(), random_seed(), random_seed())
  if (is.null(delta)) {
    delta <- max(diff(range(x)), diff(range(y)), diff(range(z))) * 1e-4
  }
  velocity_x <- ((
    generator(x = x, y = y + delta, z = z, seed = seed[3], ...) -
    generator(x = x, y = y - delta, z = z, seed = seed[3], ...)
  ) - (
    generator(x = x, y = y, z = z + delta, seed = seed[2], ...) -
    generator(x = x, y = y, z = z - delta, seed = seed[2], ...)
  )) / (2 * delta)

  velocity_y <- ((
    generator(x = x, y = y, z = z + delta, seed = seed[1], ...) -
    generator(x = x, y = y, z = z - delta, seed = seed[1], ...)
  ) - (
    generator(x = x + delta, y = y, z = z, seed = seed[3], ...) -
    generator(x = x - delta, y = y, z = z, seed = seed[3], ...)
  )) / (2 * delta)

  velocity_z <- ((
    generator(x = x + delta, y = y, z = z, seed = seed[2], ...) -
    generator(x = x - delta, y = y, z = z, seed = seed[2], ...)
  ) - (
    generator(x = x, y = y + delta, z = z, seed = seed[1], ...) -
    generator(x = x, y = y - delta, z = z, seed = seed[1], ...)
  )) / (2 * delta)

  list(x = velocity_x, y = velocity_y, z = velocity_z)
}
