# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cubic_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_cubic_2d_c', PACKAGE = 'ambient', height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

cubic_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_cubic_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

gen_cubic2d_c <- function(x, y, freq, seed) {
    .Call('_ambient_gen_cubic2d_c', PACKAGE = 'ambient', x, y, freq, seed)
}

gen_cubic3d_c <- function(x, y, z, freq, seed) {
    .Call('_ambient_gen_cubic3d_c', PACKAGE = 'ambient', x, y, z, freq, seed)
}

perlin_2d_c <- function(height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_perlin_2d_c', PACKAGE = 'ambient', height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

perlin_3d_c <- function(height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_perlin_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

gen_perlin2d_c <- function(x, y, freq, seed, interp) {
    .Call('_ambient_gen_perlin2d_c', PACKAGE = 'ambient', x, y, freq, seed, interp)
}

gen_perlin3d_c <- function(x, y, z, freq, seed, interp) {
    .Call('_ambient_gen_perlin3d_c', PACKAGE = 'ambient', x, y, z, freq, seed, interp)
}

simplex_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_simplex_2d_c', PACKAGE = 'ambient', height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

simplex_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_simplex_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

simplex_4d_c <- function(height, width, depth, time, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_simplex_4d_c', PACKAGE = 'ambient', height, width, depth, time, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

gen_simplex2d_c <- function(x, y, freq, seed) {
    .Call('_ambient_gen_simplex2d_c', PACKAGE = 'ambient', x, y, freq, seed)
}

gen_simplex3d_c <- function(x, y, z, freq, seed) {
    .Call('_ambient_gen_simplex3d_c', PACKAGE = 'ambient', x, y, z, freq, seed)
}

gen_simplex4d_c <- function(x, y, z, t, freq, seed) {
    .Call('_ambient_gen_simplex4d_c', PACKAGE = 'ambient', x, y, z, t, freq, seed)
}

value_2d_c <- function(height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_value_2d_c', PACKAGE = 'ambient', height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

value_3d_c <- function(height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_value_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

gen_value2d_c <- function(x, y, freq, seed, interp) {
    .Call('_ambient_gen_value2d_c', PACKAGE = 'ambient', x, y, freq, seed, interp)
}

gen_value3d_c <- function(x, y, z, freq, seed, interp) {
    .Call('_ambient_gen_value3d_c', PACKAGE = 'ambient', x, y, z, freq, seed, interp)
}

white_2d_c <- function(height, width, seed, freq, pertube, pertube_amp) {
    .Call('_ambient_white_2d_c', PACKAGE = 'ambient', height, width, seed, freq, pertube, pertube_amp)
}

white_3d_c <- function(height, width, depth, seed, freq, pertube, pertube_amp) {
    .Call('_ambient_white_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, pertube, pertube_amp)
}

white_4d_c <- function(height, width, depth, time, seed, freq, pertube, pertube_amp) {
    .Call('_ambient_white_4d_c', PACKAGE = 'ambient', height, width, depth, time, seed, freq, pertube, pertube_amp)
}

gen_white2d_c <- function(x, y, freq, seed) {
    .Call('_ambient_gen_white2d_c', PACKAGE = 'ambient', x, y, freq, seed)
}

gen_white3d_c <- function(x, y, z, freq, seed) {
    .Call('_ambient_gen_white3d_c', PACKAGE = 'ambient', x, y, z, freq, seed)
}

gen_white4d_c <- function(x, y, z, t, freq, seed) {
    .Call('_ambient_gen_white4d_c', PACKAGE = 'ambient', x, y, z, t, freq, seed)
}

worley_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp) {
    .Call('_ambient_worley_2d_c', PACKAGE = 'ambient', height, width, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp)
}

worley_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp) {
    .Call('_ambient_worley_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, dist, value, dist2ind, jitter, pertube, pertube_amp)
}

gen_worley2d_c <- function(x, y, freq, seed, dist, value, dist2ind, jitter) {
    .Call('_ambient_gen_worley2d_c', PACKAGE = 'ambient', x, y, freq, seed, dist, value, dist2ind, jitter)
}

gen_worley3d_c <- function(x, y, z, freq, seed, dist, value, dist2ind, jitter) {
    .Call('_ambient_gen_worley3d_c', PACKAGE = 'ambient', x, y, z, freq, seed, dist, value, dist2ind, jitter)
}

