# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cubic_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_cubic_2d_c', PACKAGE = 'ambient', height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

cubic_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_cubic_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

perlin_2d_c <- function(height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_perlin_2d_c', PACKAGE = 'ambient', height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

perlin_3d_c <- function(height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_perlin_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

simplex_2d_c <- function(height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_simplex_2d_c', PACKAGE = 'ambient', height, width, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

simplex_3d_c <- function(height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_simplex_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

simplex_4d_c <- function(height, width, depth, time, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_simplex_4d_c', PACKAGE = 'ambient', height, width, depth, time, seed, freq, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

value_2d_c <- function(height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_value_2d_c', PACKAGE = 'ambient', height, width, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

value_3d_c <- function(height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp) {
    .Call('_ambient_value_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, interp, fractal, octaves, lacunarity, gain, pertube, pertube_amp)
}

white_2d_c <- function(height, width, seed, freq, pertube, pertube_amp) {
    .Call('_ambient_white_2d_c', PACKAGE = 'ambient', height, width, seed, freq, pertube, pertube_amp)
}

white_3d_c <- function(height, width, depth, seed, freq, pertube, pertube_amp) {
    .Call('_ambient_white_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, pertube, pertube_amp)
}

white_4d_c <- function(height, width, depth, time, seed, freq, pertube, pertube_amp) {
    .Call('_ambient_white_4d_c', PACKAGE = 'ambient', height, width, depth, time, seed, freq, pertube, pertube_amp)
}

worley_2d_c <- function(height, width, seed, freq, dist, value, dist2ind, jitter, pertube, pertube_amp) {
    .Call('_ambient_worley_2d_c', PACKAGE = 'ambient', height, width, seed, freq, dist, value, dist2ind, jitter, pertube, pertube_amp)
}

worley_3d_c <- function(height, width, depth, seed, freq, dist, value, dist2ind, jitter, pertube, pertube_amp) {
    .Call('_ambient_worley_3d_c', PACKAGE = 'ambient', height, width, depth, seed, freq, dist, value, dist2ind, jitter, pertube, pertube_amp)
}

